[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\messaging_library'

[projects.library]
path = 'Source\Message Library.lvproj'

[[build.steps]]
name = 'Messaging Libraries'
type = 'lvBuildSpecAllTargets'
project = '{library}'
build_spec = 'Messaging'
